name: cook-off-prod

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: cookoff
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_URL}
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASS}
  app:
    image: cookoff:latest
    container_name: cookoff-app
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: ${PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB: cookoff
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/cookoff?authSource=admin
    volumes:
      - uploads_data:/app/public/img/recipe
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  uploads_data:
    driver: local