export enum Unit {
  MILLIGRAM = "mg",
  GRAM = "g",
  KILOGRAM = "kg",
  MILLILITER = "mL",
  CENTILITER = "cL",
  LITER = "L",
  TEASPOON = "cuillère à café",
  TABLESPOON = "cuillère à soupe",
  PINCH = "pincée",
  HANDFUL = "poignée",
  CUP = "tasse",
  CAN = "boîte",
  NONE = "Aucune unité",
}